version: "3.9"

services:
  web:
    build: ./
    ports:
      - 80:80
    depends_on:
      - db
      - cache
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
  cache:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data

volumes:
  postgres_data:
  cache_data:
